# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell_mapping',
            name='value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
