# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-17 06:07
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rc_info_auto_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rc_info',
            old_name='the_file',
            new_name='main_file',
        ),
        migrations.AddField(
            model_name='rc_info',
            name='body_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_body_file),
        ),
        migrations.AddField(
            model_name='rc_info',
            name='footer_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_footer_file),
        ),
        migrations.AddField(
            model_name='rc_info',
            name='head_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_head_file),
        ),
    ]
