# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180818_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_info',
            name='no_of_files_uploaded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
