# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rc_info_no_of_files_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_info',
            name='body_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rc_info',
            name='footer_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rc_info',
            name='head_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
