# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-23 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180820_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
