# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-24 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='replicate_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='app.user_profile')),
                ('new_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_record', to='app.rc_info')),
                ('replicated_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicated_record', to='app.rc_info')),
            ],
        ),
    ]
